/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Rectangle;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Analista de sistemas
 */
public class PanelBienvenidadDatos extends javax.swing.JPanel {

    
    private JLabel labelNombre;
    private JLabel labelApellido;
    private JLabel labelCedula;
    
    private JTextField txtNombre;
    private JTextField txtApellido;
    private JTextField txtCedula;
    
    private JLabel blanco1;
    private JLabel blanco2;
    private JLabel blanco3;
    private JLabel blanco4;
    private JLabel blanco5;
    private JLabel blanco6;
    private JLabel blanco7;
    private JLabel blanco8;
    
    public PanelBienvenidadDatos() {
        
        initComponents();
        setLayout(new GridLayout(3, 2));
        setSize(1000, 800);
        setBorder( new TitledBorder( "" ) );
        
//        blanco1 = new JLabel();
//        add (blanco1);
//        
//        blanco2 = new JLabel();
//        add (blanco2);
//        
//        blanco5 = new JLabel();
//        add (blanco5);
//        
//        blanco6 = new JLabel();
//        add (blanco6);
        
        labelCedula = new JLabel("Cédula:");
        add(labelCedula);
        
        txtCedula = new JTextField();
        add(txtCedula);
        
        labelNombre = new JLabel("Nombres:");
        add(labelNombre);
        
       txtNombre = new JTextField();
        add(txtNombre);
        
        labelApellido = new JLabel("Apellidos:");
        add(labelApellido);
        
        txtApellido = new JTextField();
        add(txtApellido);
        
//        blanco3 = new JLabel();
//        add (blanco3);
//        
//        blanco4 = new JLabel();
//        add (blanco4);
//        
//        blanco7 = new JLabel();
//        add (blanco7);
//        
//        blanco8 = new JLabel();
//        add (blanco8);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
